podman run --detach --hostname kafka --name kafka --publish 9092:9092 --publish 29092:29092 \
--env KAFKA_NODE_ID=1 --env CLUSTER_ID="MkU3OEVBNTcwNTJENDM2EV" --env KAFKA_PROCESS_ROLES=broker,controller \
--env KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092 \
--env KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 \
--env KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT \
--env KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT --env KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
--env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 --env KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
--env KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 --env KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0 \
--env KAFKA_LOG_DIRS=/tmp/kraft-combined-logs --env KAFKA_BROKER_ID=1 \
--env KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
apache/kafka:latest