name: curryware-kafka-go-processor
on:
  push:
    branches:
      - 'master'
jobs:
  build-go-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - run: go version

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Build and Push
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build Docker Image
        run: |
          docker buildx build --push -t scotcurry4/curryware-kafka-go-processor:${{ github.run_number }} \
          --platform linux/amd64 \
          --build-arg DD_VERSION=${{ github.run_number }} \
          --build-arg DD_GIT_REPOSITORY_URL="github.com/scotcurry/curryware-kafka-go-processor" \
          --build-arg DD_GIT_COMMIT_SHA=${{ github.sha }} \
          -f Dockerfile .
          
      - name: Get manifest files
        uses: actions/checkout@v4
        with:
          repository: 'scotcurry/k8s-manifests'
          path: '${{ github.workspace }}/k8s-manifests'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: 'main'
      - run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/k8s-manifests
          ls ${{ github.workspace }} -la
          # sed pattern to update manifest versions - 's/version: \"[[:digit:]]*\"/version: \"20\"/g'
          # Site to test sed commands - https://sed.js.org/
          echo 'Setting Version: ${{ github.run_number }}'
          sed -i -e 's/version: \"[[:digit:]]*\"/version: \"${{ github.run_number }}\"/g' ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-kafka-go-processor.yaml
          echo 'Updating image version'
          sed -i -e 's/scotcurry4\/curryware-kafka-go-processor\:[[:digit:]]*/scotcurry4\/curryware-kafka-go-processor\:${{ github.run_number }}/g' ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-kafka-go-processor.yaml
          cat ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-kafka-go-processor.yaml
          echo "Committed curryware-kafka-processor $(date +"%Y-%m-%d %T") - Short SHA: ${{ github.sha }}" > commit_file.txt
          git config user.name "scotcurry"
          git config user.email "scotcurry4@gmail.com"
          git commit -a -F commit_file.txt
          git push
